### ISSUE TITLE
Traceback Call error; line 13

### ISSUE THREAD

**Issue by Seagypt** [Cr7pt0nic/value-village#4]
Traceback (most recent call last):
  File "/Users/anonymousanon/Downloads/Valu3V1ll1an/automate.py", line 13, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'

chromedrive folder is located in the same folder as automate.py script

**Comment by Cr7pt0nic** [comment]
Did you try moving the chromedriver into the "chromedrive/" folder? Also try doing this

```
pip3 install webdriver_manager
```

**Comment by Cr7pt0nic** [comment]
fixed
